[package]
name = "shanan-macro"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true

[dependencies]

toml = "0.9"
proc-macro2 = { version="1.0", features = ["proc-macro"] }
quote = "1.0"
syn = { version = "2.0", features = ["full"] }